allowBuilds:
  cpu-features: false
  msgpackr-extract: false
  onnxruntime-node: false
  protobufjs: false
  sharp: false
  ssh2: false
minimumReleaseAgeExclude:
  - effect
  - "@effect/*"
packages:
  - packages/*
  - apps/*
  - e2e
supportedArchitectures:
  os: [linux]
  cpu: [x64, arm64]
  libc: [glibc]
