import { NodeServices } from '@effect/platform-node'
import { Gherkin, Given, it, layer, makeFeature, Then, When } from '@systemfsoftware/effect-gherkin-spec'
import { PackageVersion, RelativePath, RepoRoot, SurfaceStore, VersionSurface } from '@systemfsoftware/release-language'
import { SurfaceStoreLive } from '@systemfsoftware/workspace-adapter'
import { Effect, Layer } from 'effect'
import { FileSystem } from 'effect/FileSystem'
import * as Match from 'effect/Match'
import { Path } from 'effect/Path'
import * as S from 'effect/Schema'
import type { SchemaError } from 'effect/Schema'
import { expect } from 'vitest'

const Feature = makeFeature({ it, layer })

const ROOT_TEXT = await Effect.runPromise(
  Effect.provide(
    Effect.gen(function*() {
      const fs = yield* FileSystem
      return yield* fs.makeTempDirectory({ prefix: 'workspace-adapter-cargo-' })
    }),
    NodeServices.layer,
  ),
)
const root = RepoRoot.make(ROOT_TEXT)
const live = Layer.merge(SurfaceStoreLive(root).pipe(Layer.provide(NodeServices.layer)), NodeServices.layer)

const CARGO = RelativePath.make('Cargo.toml')

const MANIFEST = `[workspace]
members = ["crates/*"]

[workspace.package]
version = "1.1.0"
edition = "2021"
`

const LITERAL = `[package]
name = "core"
version = "1.1.0"
edition = "2021"
`

const INHERITING = `[package]
name = "api"
version.workspace = true
edition = "2021"
`

const LOCK = `# This file is automatically @generated by Cargo.
version = 3

[[package]]
name = "core"
version = "1.1.0"

[[package]]
name = "serde"
version = "1.5.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc"
`

const BROKEN_LOCK = `version = 3

[[package]]
name = "core"
`

const resetTo = (files: ReadonlyArray<readonly [string, string]>) =>
  Effect.gen(function*() {
    const fs = yield* FileSystem
    const path = yield* Path
    yield* Effect.when(fs.remove(ROOT_TEXT, { recursive: true }), fs.exists(ROOT_TEXT))
    yield* Effect.forEach(files, ([file, text]) =>
      Effect.gen(function*() {
        const full = path.join(ROOT_TEXT, file)
        yield* fs.makeDirectory(path.dirname(full), { recursive: true })
        yield* fs.writeFileString(full, text)
      }), { discard: true })
  })

const readFixture = (file: string) =>
  Effect.gen(function*() {
    const fs = yield* FileSystem
    const path = yield* Path
    return yield* fs.readFileString(path.join(ROOT_TEXT, file))
  })

const lockExists = Effect.gen(function*() {
  const fs = yield* FileSystem
  const path = yield* Path
  return yield* fs.exists(path.join(ROOT_TEXT, 'Cargo.lock'))
})

const decodeSurface: Effect.Effect<VersionSurface, SchemaError> = S.decodeUnknownEffect(VersionSurface)({
  kind: 'cargo',
  path: 'Cargo.toml',
})

const bumpSurface = (version: string) =>
  Effect.gen(function*() {
    const surfaces = yield* SurfaceStore
    const surface = yield* decodeSurface
    return yield* surfaces.writeSurface(CARGO, surface, PackageVersion.make(version))
  })

const readCargoSurface = Effect.gen(function*() {
  const surfaces = yield* SurfaceStore
  const surface = yield* decodeSurface
  return yield* surfaces.readSurface(CARGO, surface)
})

const failUnexpected = (message: string): never => {
  throw new Error(message)
}

const bumpOutcome = (version: string) =>
  Effect.match(bumpSurface(version), {
    onFailure: (refusal) => ({ _tag: 'failed' as const, refusal }),
    onSuccess: (write) => ({ _tag: 'ok' as const, write }),
  })

const readOutcome = Effect.match(readCargoSurface, {
  onFailure: (refusal) => ({ _tag: 'failed' as const, refusal }),
  onSuccess: (version) => ({ _tag: 'ok' as const, version }),
})

const WORKSPACE_FILES: ReadonlyArray<readonly [string, string]> = [
  ['Cargo.toml', MANIFEST],
  ['crates/core/Cargo.toml', LITERAL],
  ['crates/api/Cargo.toml', INHERITING],
]

Feature('Cargo surface rewrites').body(({ scenario }) => {
  scenario(
    'A bump rewrites the workspace version, literal members and lock entries',
    { scenarioLayer: live },
    Gherkin.Do.pipe(
      Given('a cargo workspace with a literal member, an inheriting member and a lock')(
        'ready',
        () => resetTo([...WORKSPACE_FILES, ['Cargo.lock', LOCK]]),
      ),
      When('the cargo surface is bumped to 2.0.0')('outcome', () => bumpOutcome('2.0.0')),
      Then('the manifest, the literal member and the lock all carry 2.0.0')((s) =>
        Match.value(s.outcome).pipe(
          Match.tag('ok', () =>
            Effect.gen(function*() {
              expect(yield* readFixture('Cargo.toml')).toContain('version = "2.0.0"')
              expect(yield* readFixture('crates/core/Cargo.toml')).toContain('version = "2.0.0"')
              expect(yield* readFixture('crates/api/Cargo.toml')).toContain('version.workspace = true')
              expect(yield* readFixture('Cargo.lock')).toContain('name = "core"\nversion = "2.0.0"')
              expect(yield* readFixture('Cargo.lock')).toContain('name = "serde"\nversion = "1.5.0"')
              expect(yield* readFixture('Cargo.lock')).toContain(
                'source = "registry+https://github.com/rust-lang/crates.io-index"',
              )
            })),
          Match.tag('failed', () => Effect.sync(() => failUnexpected('expected a cargo bump'))),
          Match.exhaustive,
        )
      ),
    ),
  )

  scenario(
    'A bump without a lock file still rewrites the manifest and members',
    { scenarioLayer: live },
    Gherkin.Do.pipe(
      Given('a cargo workspace that commits no lock file')('ready', () => resetTo(WORKSPACE_FILES)),
      When('the cargo surface is bumped to 2.0.0')('outcome', () => bumpOutcome('2.0.0')),
      Then('the manifest and members move and no lock is invented')((s) =>
        Match.value(s.outcome).pipe(
          Match.tag('ok', () =>
            Effect.gen(function*() {
              expect(yield* readFixture('Cargo.toml')).toContain('version = "2.0.0"')
              expect(yield* readFixture('crates/core/Cargo.toml')).toContain('version = "2.0.0"')
              expect(yield* lockExists).toBe(false)
            })),
          Match.tag('failed', () => Effect.sync(() => failUnexpected('expected a cargo bump'))),
          Match.exhaustive,
        )
      ),
    ),
  )

  scenario(
    'A stale lock entry refuses the bump',
    { scenarioLayer: live },
    Gherkin.Do.pipe(
      Given('a cargo workspace whose lock names a member without a version')(
        'ready',
        () => resetTo([...WORKSPACE_FILES, ['Cargo.lock', BROKEN_LOCK]]),
      ),
      When('the cargo surface is bumped to 2.0.0')('outcome', () => bumpOutcome('2.0.0')),
      Then('the refusal names the stale lock')((s) =>
        Match.value(s.outcome).pipe(
          Match.tag('ok', () => Effect.sync(() => failUnexpected('expected a stale lock refusal'))),
          Match.tag('failed', (failed) =>
            Effect.sync(() => {
              expect(failed.refusal).toMatchObject({ _tag: 'VersionLockStale', path: 'Cargo.lock' })
            })),
          Match.exhaustive,
        )
      ),
    ),
  )

  scenario(
    'Reading reports a member that lags the workspace version',
    { scenarioLayer: live },
    Gherkin.Do.pipe(
      Given('a cargo workspace whose member pins an older version')('ready', () =>
        resetTo([
          ['Cargo.toml', MANIFEST],
          ['crates/core/Cargo.toml', LITERAL.replace('1.1.0', '1.0.0')],
          ['crates/api/Cargo.toml', INHERITING],
        ])),
      When('the cargo surface is read')('outcome', () => readOutcome),
      Then('the stale member version surfaces as drift')((s) =>
        Match.value(s.outcome).pipe(
          Match.tag('ok', (ok) => Effect.sync(() => expect(ok.version).toEqual('1.0.0'))),
          Match.tag('failed', () => Effect.sync(() => failUnexpected('expected a cargo read'))),
          Match.exhaustive,
        )
      ),
    ),
  )

  scenario(
    'A missing manifest refuses the bump',
    { scenarioLayer: live },
    Gherkin.Do.pipe(
      Given('a cargo workspace with no root manifest')('ready', () => resetTo([['crates/api/Cargo.toml', INHERITING]])),
      When('the cargo surface is bumped to 2.0.0')('outcome', () => bumpOutcome('2.0.0')),
      Then('the missing manifest is refused')((s) =>
        Match.value(s.outcome).pipe(
          Match.tag('ok', () => Effect.sync(() => failUnexpected('expected a missing manifest refusal'))),
          Match.tag('failed', (failed) =>
            Effect.sync(() => {
              expect(failed.refusal).toMatchObject({ _tag: 'VersionSurfaceMissing', path: 'Cargo.toml' })
            })),
          Match.exhaustive,
        )
      ),
    ),
  )

  scenario(
    'A manifest without a workspace version refuses the bump',
    { scenarioLayer: live },
    Gherkin.Do.pipe(
      Given('a cargo workspace whose manifest declares no workspace version')(
        'ready',
        () => resetTo([['Cargo.toml', '[workspace]\nmembers = ["crates/*"]\n']]),
      ),
      When('the cargo surface is bumped to 2.0.0')('outcome', () => bumpOutcome('2.0.0')),
      Then('the malformed manifest is refused')((s) =>
        Match.value(s.outcome).pipe(
          Match.tag('ok', () => Effect.sync(() => failUnexpected('expected a malformed manifest refusal'))),
          Match.tag('failed', (failed) =>
            Effect.sync(() => {
              expect(failed.refusal).toMatchObject({ _tag: 'VersionIntentMalformed', path: 'Cargo.toml' })
            })),
          Match.exhaustive,
        )
      ),
    ),
  )
})
